### ISSUE TITLE
Peak usage is delayed by one memory allocation

### ISSUE THREAD

**Issue by luxalpa** [xgillard/peak_alloc#4]
I was wondering why my Peak memory usage was lower than my current usage.

https://github.com/xgillard/peak_alloc/blob/1795139db273005d8634c9a3fe7bd1872f9a40cc/src/lib.rs#L133

`curr` in this line is actually the previous value: https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html#method.fetch_add

I don't know if there's a more elegant/efficient way to fix it other than adding an additional `load`.

**Comment by xgillard** [comment]
Hi, thank you for your feedback ! 
you are right that the relaxed memory order isnt correct given there are two resources involved and it makes sense to compare them.

 I must reckon that only the final value of the peak mem was of importance to me. So i did not pay that much attention to the current amount. 

thining it though, i believe that acquire-relsease would be the right order, but i would like to re read the specifics of these orders to make sure i pick the right one this time 😅

**Comment by luxalpa** [comment]
The issue is that the peak memory usage that this retrieves is incorrect, as it always leaves out one operation (and therefore "lags" behind), so whenever peak memory usage is printed, it is displaying the value from before the last allocation (instead of displaying the one after).
In my case memory ordering was not relevant because all the allocations in my program were single threaded.

**Comment by xgillard** [comment]
Sorry, I know it's been a loooong time since you entered this issue. I finally took some time to fix it. (version 0.2.1 will be underway soon).
